ai_provider: openai
openai_api_key: "YOUR_OPENAI_KEY_HERE"
# optional, if you want to use Gemini:
# gemini_api_key: "YOUR_GEMINI_KEY_HERE"

# and any other keys your project needs:
# webhook_url: "https://...."
# pickle_output_path: "data/pickle"
# cleanup_days: 7
# etc.
